[User]
token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTc5OTM5MzAsImV4cCI6MTcyOTUyOTkzMCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9UT1NfQUNDRVBURUQiLCJST0xFX0NPTkZJUk1FRF9FTUFJTCJdLCJ1c2VyX2lkIjoiYjg1YTlhYTgtODU1My00OTFkLWIwYzMtODZlMzNlNDMwMWNkIiwiZW1haWwiOiJiYWRib3lzdHVkaW8yOTAxQGdtYWlsLmNvbSJ9.f2rU-BozLjW2_9ayk1e0FYf3sO6Mk_jen3KZQDWEx9ESPxvH2jmh7CVf5iDAmXMK_ltkg217GRIjzTH-P3618EXyW4xdx5bt2aYxGpcWTiMaLu49OJKpoiWO3-BZOdltwAH1NWAEae1bfT-KYrrFc9abrHuR0OVxIzZ6GhzpJV1riunaVFm4mTQVaysq_NNeI3h2yIi15mOibzDQPTO_uiRzw7qJlrHrN2WX8cfRMqh5rgYuqTj0WoxCvnV3LRdN_MO9hB4ssxXsh48x8ZHYKWcTXm-nRDk573eIJs5QRsAvvXePkqtAHGQZDndKDMwhq4QgLC3Bukx20_2yjryhj6c0KkP9JYw7TyMbXhk8TA_bQxRgSn_M-7CGBJ6EUfIy0IsrrvR5uxSYolkFrMfD52_JW2D0Y2yCAtYxHKkoC1ESK1uzZ2JADnhPOJfBC3zJvPzELfkzhXzRyhtJXguog-4ZLUxAsVBDQLAm03wgewJb5olR7s1Y-TPMg1stn5jrRf9-v-J-BLUQje9sUbXR2ZKRFdrrupEgws68PLEphVKzNEBUxF-a1bzl0El5zHyqTOZ1BcwNfjxrqO5VwBkme_ZnR1nM3bTf50PTRYh7j2lgRYTyEREUE-0uGBGjhiWpIjIZoqJPq_QXsLxEhrOFYMbTR_JXW51bpSgMCIWZkvE

[Settings]
lucky pot = True
achievements = True

[Url]
login = https://dashboard.honeygain.com/api/v1/users/tokens
pot = https://dashboard.honeygain.com/api/v1/contest_winnings
balance = https://dashboard.honeygain.com/api/v1/users/balances
achievements = https://dashboard.honeygain.com/api/v1/achievements/
achievement_claim = https://dashboard.honeygain.com/api/v1/achievements/claim

