name: CL
on:
  push:
    branches:
      - main
   
jobs:
  CL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Run HoneygainPot
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }} # <- DO NOT enter your email here, it may leak your information
          PASS: ${{ secrets.PASS }} # <- DO NOT enter your password here, it may leak your information
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # <- DO NOT enter your JWT Token here, it may leak your information
          IsJWT: ${{ secrets.JWT_TOKEN }} # <- DO NOT Touch THIS