name: CL
on:
  push:
    branches:
      - main
   
jobs:
  CodeCL:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests 
      - name: Run HoneygainPot
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }} # <- DO NOT enter your email here, it may leak your information
          PASS: ${{ secrets.PASS }} # <- DO NOT enter your password here, it may leak your information
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # <- DO NOT enter your JWT Token here, it may leak your information
          IsJWT: 1 # <- 0 = Use Mail and Pass ; 1 = Use Token (Default is 1)
