name: Daily claim
on:
  schedule:
    - cron: '0 14 * * *' # UTC Time

jobs:
  HoneyGainPot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python main.py
        env:
          MAIL_JWD: ${{ secrets.MAIL_JWD }}
          PASS_JWD: ${{ secrets.PASS_JWD }}
